[book]
title = "Cassa Documentation"
authors = ["Cassa Team"]
language = "en"
src = "src"

[build]
build-dir = "book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/FrancescoMangia/cassa-docs"
additional-js = ["mermaid.min.js", "mermaid-init.js", "solidity.min.js"]
